### ISSUE TITLE
Integration with CrossContainerExtension - docs?

### ISSUE THREAD

**Issue by pamil** [FriendsOfBehat/ServiceContainerExtension#20]

**Comment by warslett** [comment]
+1 I pressume the idea with CrossContainerExtension is that it allows you to use services belonging to the kernel's container including the entity manager etc. Unfortunately the repo doesn't explain in anyway how to use it. Since Symfony 4 makes all services private by default, behat has become pretty useless because you can't access those services you need to create test data or interact with the application in any way.

**Comment by jcornide** [comment]
Hi,

I like the FOB projects but the lack of documentation is really an issue here. I don't know how to inject the entity manager to a behat service and I didn't find any documentation about it

**Comment by warslett** [comment]
@jcornide there is an open issue regarding this on the symfony behat extension which you might want to follow: https://github.com/Behat/Symfony2Extension/issues/128

**Comment by pamil** [comment]
CrossContainerExtension is now deprecated, please take a look at the brand new FOB/SymfonyExtension v2 which solves issues with private services, autowiring and provides a smoother learning curve (and there are some docs)!
